//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalPlotter.PmwLatencyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LatestData", Namespace="http://schemas.datacontract.org/2004/07/LatencyService.Model")]
    [System.SerializableAttribute()]
    public partial struct LatestData : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SignalPlotter.PmwLatencyService.LatencySample emaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SignalPlotter.PmwLatencyService.LatencySample latestField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SignalPlotter.PmwLatencyService.LatencySample ema {
            get {
                return this.emaField;
            }
            set {
                if ((this.emaField.Equals(value) != true)) {
                    this.emaField = value;
                    this.RaisePropertyChanged("ema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SignalPlotter.PmwLatencyService.LatencySample latest {
            get {
                return this.latestField;
            }
            set {
                if ((this.latestField.Equals(value) != true)) {
                    this.latestField = value;
                    this.RaisePropertyChanged("latest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LatencySample", Namespace="http://schemas.datacontract.org/2004/07/LatencyService.Model")]
    [System.SerializableAttribute()]
    public partial struct LatencySample : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> rttMsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SignalPlotter.PmwLatencyService.SampleStatus statusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> rttMs {
            get {
                return this.rttMsField;
            }
            set {
                if ((this.rttMsField.Equals(value) != true)) {
                    this.rttMsField = value;
                    this.RaisePropertyChanged("rttMs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SignalPlotter.PmwLatencyService.SampleStatus status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SampleStatus", Namespace="http://schemas.datacontract.org/2004/07/LatencyService.Model")]
    public enum SampleStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nonexistent = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimedOut = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Good = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PmwLatencyService.ILatencyServiceContract")]
    public interface ILatencyServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatencyServiceContract/LatestLatency", ReplyAction="http://tempuri.org/ILatencyServiceContract/LatestLatencyResponse")]
        SignalPlotter.PmwLatencyService.LatestData LatestLatency();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatencyServiceContract/LatestLatency", ReplyAction="http://tempuri.org/ILatencyServiceContract/LatestLatencyResponse")]
        System.Threading.Tasks.Task<SignalPlotter.PmwLatencyService.LatestData> LatestLatencyAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILatencyServiceContractChannel : SignalPlotter.PmwLatencyService.ILatencyServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LatencyServiceContractClient : System.ServiceModel.ClientBase<SignalPlotter.PmwLatencyService.ILatencyServiceContract>, SignalPlotter.PmwLatencyService.ILatencyServiceContract {
        
        public LatencyServiceContractClient() {
        }
        
        public LatencyServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LatencyServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LatencyServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LatencyServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SignalPlotter.PmwLatencyService.LatestData LatestLatency() {
            return base.Channel.LatestLatency();
        }
        
        public System.Threading.Tasks.Task<SignalPlotter.PmwLatencyService.LatestData> LatestLatencyAsync() {
            return base.Channel.LatestLatencyAsync();
        }
    }
}
